name: CI

on: push

jobs:

  Linting:
    name: Check Linting
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-versions: ['3.10', '3.11']

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      
      - name : Run flake8
        run: |
          flake8 app.py
